### PR TITLE
fix show 6 latest logins

### LINKED ISSUE #175: Show 6 latest logins doesn't work
When I click on `6 latest logins`
Image

and redirected to the Manager Page, Foxtrick go to CSP error when simulate click on `6 latest logins` button.

Image

### PR DESCRIPTION
**Pull request by odrail**
Fixes #175

### CODE REVIEW

File: content/shortcuts-and-tweaks/team-popup-links.js [hunk 1]
```diff
@@ -166,8 +166,14 @@ Foxtrick.modules['TeamPopupLinks'] = {
...
-			let a = Foxtrick.getMBElement(doc, 'lnkShowLogins');
-			a && a.click();
+			const s = document.createElement("script");
+			if (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.getURL) {
+				s.src = chrome.runtime.getURL("content/resources/js/ShowOldConnectionsInjected.js");
+			} else if (typeof browser !== "undefined" && browser.runtime && browser.runtime.getURL) {
+				s.src = browser.runtime.getURL("content/resources/js/ShowOldConnectionsInjected.js");
+			}
+			(document.head || document.documentElement).appendChild(s);
+			s.onload = () => s.remove();
```
Comment (unnecessarydave) [inline content/shortcuts-and-tweaks/team-popup-links.js:176]:
```suggestion
		// show last 6 logins
		if (Foxtrick.isPage(doc, 'managerPage') && /ShowOldConnections=true/i.test(doc.URL)) {
			let scriptTag = Foxtrick.util.inject.jsLink(doc, Foxtrick.InternalPath + 'resources/js/ShowOldConnectionsInjected.js');
			scriptTag.onload  = () => scriptTag.remove();
```

**Review by unnecessarydave — APPROVED** [review]
Cheers.

**Comment by unnecessarydave** [comment]
Okay, there is a problem that **I** have created by making you switch from your message passing method to using `onLoad`.  It works on inital load, but not on (the much faster) page reload - it's a timing thing. Possibly caused by HT's recent change where their inline `<script>` tags are commented out at load, and later uncommented by some sort of script 'loader'.

When I was testing yesterday it worked fine every time, but it turns out that was because I had the console open 😞 

I'll just push an update to your branch that switches to `document.readyState` and it's associated event.  I don't want to waste any more of your time with my meddling.

**Comment by odrail** [comment]
`document.readyState === 'completed'` is an alternative to `load` event as described [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#readystatechange_as_an_alternative_to_load_event). How do you think to fix it?

**Review by unnecessarydave — CHANGES_REQUESTED** [review]
Like so.

**Comment by odrail** [comment]
I can't replicate the bug. Could you share the steps with me (a video would be even better)?
